baseURL: 'https://psgclub.com/'

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languages:
  fr:
    languageCode: fr-CA
    languageDirection: ltr
    languageName: French
    contentDir: content/fr
    params:
      subtitle: French
      fabformURL: 'https://assets.mailerlite.com/jsonp/545609/forms/96230485994243345/subscribe'
      subscribeTrackView: 'https://assets.mailerlite.com/jsonp/545609/forms/96230485994243345/track-view'
      blogPageURL: fr/blog
      contactLink: fr/join
      footerContact:
        topTitle: Rejoins-nous
        title: Vis ta passion au sein de la communauté PSG de Montréal
        button: S'inscrire
        link: fr/join
      titleAddition: Club de Supporter du PSG à Montréal
      images:
        - images/logo.png
      description: >-
        Supporter le PSG à Montréal, partager notre passion et vibrer tous ensemble !
    title: PSG Club Montréal
    description: Supporter le PSG à Montréal, partager notre passion et vibrer tous ensemble !
    weight: 1
  en:
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    contentDir: content/en
    params:
      subtitle: English
      fabformURL: 'https://assets.mailerlite.com/jsonp/545609/forms/96715455318722176/subscribe'
      subscribeTrackView: 'https://assets.mailerlite.com/jsonp/545609/forms/96715455318722176/track-view'
      blogPageURL: en/blog
      contactLink: en/join
      footerContact:
        topTitle: Join us
        title: Live your passion within the PSG Montreal community
        button: Join
        link: en/join
      images:
        - images/logo.png
      titleAddition: PSG fan club in Montréal
      description: >-
        Supporting PSG in Montreal, sharing our passion and cheering together!
    title: PSG Club Montreal
    description: Supporting PSG in Montreal, sharing our passion and cheering together!
    weight: 2
staticDir:
  - static/


disableAliases: true
disableHugoGeneratorInject: false
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
paginate: 6
rssLimit: 10
outputs:
  home:
    - HTML
    - RSS
    - REDIRECTS
    - HEADERS
mediaTypes:
  text/netlify:
    suffixes:
      - ''
    delimiter: ''
outputFormats:
  REDIRECTS:
    mediatype: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
caches:
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 10s
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
permalinks:
  blog: 'blog/:title/'
minify:
  tdewolff:
    html:
      keepWhitespace: false
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: categories
      weight: 100
    - name: date
      weight: 10
build:
  writeStats: true
_template: config_template
