main:
  - name: menu-home
    url: ""
    weight: 1
  - name: menu-event
    url: "#event"
    weight: 2
  - name: menu-association
    url: "#about"
    weight: 3
  - name: menu-blog
    url: "blog"
    weight: 4
sitemap:
  - name: menu-home
    url: ""
    weight: 1
  - name: join
    url: "join"
    weight: 2
  - name: menu-event
    url: "event"
    weight: 3
  - name: menu-blog
    url: "blog"
    weight: 4

