titleSeparator: '-'
images:
  - favicon.ico
ogLocale: fr
titleHome: PSG Club Montreal
twitterSite: '@psgclubmontreal'
twitterCreator: '@psgclubmontreal'
schemaType: Organization
schemaName: PSG Club Montreal
schemaAuthor: PSG Club Montreal
schemaAuthorTwitter: 'https://twitter.com/psgclubmontreal'
schemaAuthorLinkedIn: 'https://www.linkedin.com/company/psgclubmontreal/'
schemaLocale: fr
schemaLogo: images/logo.png
schemaLogoWidth: 1000
schemaLogoHeight: 1000
schemaImage: images/logo.png
schemaImageWidth: 1000
schemaImageHeight: 1000
schemaTwitter: 'https://twitter.com/psgclubmontreal'
schemaLinkedIn: 'https://www.linkedin.com/company/psgclubmontreal/'
themeColor: '#3ac58d'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: '320'
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - '480'
  - '720'
  - '1080'
  - '1280'
  - '1600'
  - '2048'
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: false
alertDismissable: true
alertText: >-
  Ici c'est Paris <a class="alert-link"
  href="https://www.psgclub.com" target="_blank" rel="noopener">Inscris toi→</a>
copyright: © PSG Club Montreal 2023
footerLogo: images/site-navigation/logo.png
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/site-navigation/logo.png
address:
  address: >
    429 Avenue Viger E,  <br>

    Montréal, QC H2L 2N9
  email: info@psgclubmontreal.com
social:
  - icon: fa-brands fa-discord
    url: 'https://instagram.com/psg_clubmontreal'
    weight: 1
  - icon: fa-brands fa-instagram
    url: 'https://instagram.com/psg_clubmontreal'
    weight: 2
  - icon: fa-brands fa-square-facebook
    url: 'https://facebook.com/psgclubmontreal'
    weight: 3
  - icon: fa-brands fa-linkedin
    url: 'https://www.linkedin.com/company/psgclubmontreal'
    weight: 4
  - icon: fa-brands fa-twitter-square
    url: 'https://twitter.com/psgclubmontreal'
    weight: 5
_template: parameters_template
